# Scatter Plot

## Calculation

```{r,eval=TRUE}
library(lagci)
data("heart_data")
data("step_data")
result <- lagci::calculate_lagged_correlation(
  y = heart_data$heart,
  x = step_data$step,
  time2 = heart_data$time,
  time1 = step_data$time,
  time_tol = 0.5,
  step = 1/60,
  align_method = "linear",
  cor_method = "spearman"
)
```

## Scatter Plot

```{r,eval=TRUE}
max_scatter <- lagged_scatter_plot(object = result,
                    x_name = "x_name",
                    y_name = "y_name",
                    which = "max",
                    hex = TRUE)

global_scatter <- lagged_scatter_plot(object = result,
                    x_name = "x_name",
                    y_name = "y_name",
                    which = "global",
                    hex = TRUE)

hex_no <- lagged_scatter_plot(object = result,
                    x_name = "x_name",
                    y_name = "y_name",
                    which = "max",
                    hex = FALSE)

max_scatter;global_scatter;hex_no
```