project:
  type: book
  output-dir: docs

book:
  title: "lagci Tutorial"
  reader-mode: false
  page-footer:
    left: |
      lagci is developed by Shen Lab @ Nanyang Technological University Singapore.
    right: |
      © 2025 <a href="https://www.shen-lab.org/">Shen Lab</a>.
  author: "Xiaotao SHEN & Zirui QIANG & Shunpeng BAI & Yitong WU"
  date: "2025-08-04"
  favicon: "images/lagci_logo.png"
  url: http://www.shen-lab.org/lagci-tutorial/
  sidebar:
    search: true
    logo: "images/lagci_logo.png"
  repo-url: https://github.com/jaspershen-lab/lagci-tutorial
  repo-actions: [edit, issue, source] 
  image: "images/lagci_logo.pn"
    
  chapters:
    - index.qmd
    
    - part: "Install lagci and Docker"
      chapters:
        - 1-1-Installation and Update.qmd
        - 1-2-Docker Version of lagci.qmd
        # - 1-3-Docker Version of lagcishiny.qmd
        - 1-4-Build your own Docker Image.qmd
        # - references.qmd

    - part: "Raw Data Processing and Preview"
      chapters:
        - 2-1-Raw Data Processing.qmd
        - 2-2-Time Plot.qmd

    - part: "Calculation and Plotting"
      chapters:
        - 3-1-Calculation.qmd
        - 3-2-Extract Data form Calculation Result.qmd
        - 3-3-Alignment Plot.qmd
        - 3-4-Scatter Plot.qmd
        - 3-5-Evaluated Plot.qmd
        
    - part: "lagcishiny Web Application"
      chapters:
        - 4-1-Installation of lagcishiny.qmd
        - 1-3-Docker Version of lagcishiny.qmd
        - 4-2-Run lagcishiny on your PC.qmd
        - 4-3-Deploy lagcishiny on your server.qmd
        
    - FAQ and Citation.qmd

bibliography: references.bib

format:
  html:
    theme:
      light: cosmo
      dark: superhero
    code-link: true

editor: visual